name: Playwright Tests

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Node kur
      uses: actions/setup-node@v4
      with:
        node-version: 24

    - name: Paketleri yükle
      run: npm install

    - name: Depoları temizle
      run: |
        sudo rm -f /etc/apt/sources.list.d/azure-cli.list /etc/apt/sources.list.d/microsoft-prod.list || true
        sudo apt-get update || true

    - name: Playwright kur
      run: npx playwright install --with-deps

    - name: Testleri çalıştır
      run: npx playwright test
